"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AdminPage, StatusBadge, TableCell, TableHead } from "@/components/admin/AdminPage";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { DataTable } from "@/components/ui/DataTable";
import { EmptyState } from "@/components/ui/EmptyState";
import { FormField } from "@/components/forms/FormField";
import { LoadingState } from "@/components/ui/LoadingState";
import { getApiErrorMessage } from "@/services/api-client";
import { applicationsService } from "@/services/applications.service";
import type { Application, ApplicationUser } from "@/types/application";

export function ApplicationsList() { const [items, setItems] = useState<Application[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); useEffect(() => { applicationsService.list().then((r) => setItems(r.data)).catch((e) => setError(getApiErrorMessage(e))).finally(() => setLoading(false)); }, []); return <AdminPage title="Applications" description="Services registered in Central IAM. OAuth clients are managed separately in a later phase." action={{ href: "/applications/new", label: "Register application" }}>{error ? <Alert>{error}</Alert> : loading ? <LoadingState /> : !items.length ? <EmptyState message="No applications registered." /> : <DataTable><thead><tr><TableHead>Application</TableHead><TableHead>Slug</TableHead><TableHead>Status</TableHead><TableHead>Action</TableHead></tr></thead><tbody>{items.map((a) => <tr key={a.id}><TableCell>{a.name}</TableCell><TableCell><code>{a.slug}</code></TableCell><TableCell><StatusBadge status={a.status} /></TableCell><TableCell><Link className="underline" href={`/applications/${a.id}`}>Manage</Link></TableCell></tr>)}</tbody></DataTable>}</AdminPage>; }

export function ApplicationForm({ id }: { id?: string }) { const router = useRouter(); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [description, setDescription] = useState(""); const [loading, setLoading] = useState(Boolean(id)); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); useEffect(() => { if (id) applicationsService.get(id).then((a) => { setName(a.name); setSlug(a.slug); setDescription(a.description ?? ""); }).catch((e) => setError(getApiErrorMessage(e))).finally(() => setLoading(false)); }, [id]); async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); try { const input = { name, slug, description: description || null }; const a = id ? await applicationsService.update(id, input) : await applicationsService.create(input); router.push(`/applications/${a.id}`); } catch (err) { setError(getApiErrorMessage(err)); } finally { setSaving(false); } } return <AdminPage title={id ? "Edit application" : "Register application"}>{loading ? <LoadingState /> : <form onSubmit={submit} className="max-w-xl space-y-5 rounded-lg border bg-white p-6">{error ? <Alert>{error}</Alert> : null}<FormField name="name" label="Name" value={name} onChange={(e) => setName(e.target.value)} required /><FormField name="slug" label="Slug" value={slug} onChange={(e) => setSlug(e.target.value)} required /><div><label htmlFor="description" className="mb-1.5 block text-sm font-medium text-slate-700">Description</label><textarea id="description" name="description" value={description} onChange={(e) => setDescription(e.target.value)} className="min-h-28 w-full rounded-md border border-slate-300 p-3" /></div><Button isLoading={saving}>Save application</Button></form>}</AdminPage>; }

export function ApplicationDetails({ id }: { id: string }) { const [application, setApplication] = useState<Application | null>(null); const [users, setUsers] = useState<ApplicationUser[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); useEffect(() => { Promise.all([applicationsService.get(id), applicationsService.users(id)]).then(([a, u]) => { setApplication(a); setUsers(u); }).catch((e) => setError(getApiErrorMessage(e))); }, [id]); async function toggle() { if (!application) return; setBusy(true); try { setApplication(await applicationsService.changeStatus(id, application.status === "active" ? "deactivate" : "activate")); } catch (e) { setError(getApiErrorMessage(e)); } finally { setBusy(false); } } return <AdminPage title={application?.name ?? "Application"} action={{ href: `/applications/${id}/edit`, label: "Edit application" }}>{error ? <Alert>{error}</Alert> : !application ? <LoadingState /> : <div className="space-y-6"><section className="rounded-lg border bg-white p-6"><div className="flex items-center justify-between"><div><code className="text-sm">{application.slug}</code><div className="mt-2"><StatusBadge status={application.status} /></div></div><Button variant={application.status === "active" ? "danger" : "primary"} isLoading={busy} onClick={toggle}>{application.status === "active" ? "Deactivate" : "Activate"}</Button></div><p className="mt-5 text-sm text-slate-600">{application.description || "No description."}</p></section><section><h2 className="mb-3 text-lg font-semibold">Users with access</h2>{users.length ? <DataTable><thead><tr><TableHead>User</TableHead><TableHead>Account</TableHead></tr></thead><tbody>{users.map((u) => <tr key={u.id}><TableCell><Link href={`/users/${u.id}`}>{u.name}</Link><div className="text-slate-500">{u.email}</div></TableCell><TableCell><StatusBadge status={u.status} /></TableCell></tr>)}</tbody></DataTable> : <EmptyState message="No users have access." />}</section><Link href="/application-access" className="inline-flex rounded-md bg-slate-900 px-4 py-2 text-sm text-white">Manage access</Link></div>}</AdminPage>; }
